### PR TITLE
navbar-center-intens

### LINKED ISSUE #59: Remove Nav Menu Padding
# Description
The hamburger menu is not centered on mobile viewports.

Edit: Sorry, it looks like this is an issue on Desktop as well.

Edit 2: Sorry again, I should have renamed the title earlier to "Remove Nav Menu Padding"

**Severity: Minor**

## Expected Behaviour

- Nav Items are centered

## Actual Behaviour

- Nav Items are not centered

## Screenshots

image

## To Reproduce

1. Go to any Migram page.
2. Change the viewport to mobile via your browser's dev tools.
3. Click on the hamburger menu.
4. Inspect the nav items.

### PR DESCRIPTION
**Pull request by composerrequirer**
Here goes my first contribution to a project, I hope I made everything right.

Fixes #59

### CODE REVIEW

**Review by davidtaing — CHANGES_REQUESTED** [review]
Hi @composerrequirer,
Sorry, I just realised that the issue affects Desktop as well. Otherwise well done!

Can move this line out of the media query and into the parent NavStyles?

Just to double check with you, how did you find out about this project? And are you a part of Code Sydney?

**Comment by composerrequirer** [comment]
So, do you want the buttons to be centralized on the screen for desktops as well?

**Comment by composerrequirer** [comment]
I'm not from Code Sydney.

**Review by composerrequirer — COMMENTED** [review]
Centralized buttons #fixes 60

**Comment by davidtaing** [comment]
```tsx
const NavStyles = styled.ul<Pick<NavProps, any>>`
  display: flex;
  justify-content: space-between;
  justify-self: end;
  align-items: center;
  font-weight: 500;
  text-transform: lowercase;
  padding: 0px; // <----------- 2. To here please!

  a {
    margin: 0 1rem;
  }
  button {
    margin: 0 1rem;
  }
  @media (max-width: 820px) {
    padding: 0px; // <--------- 1. Can you please move this up?
    width: 100vw;
    position: absolute;
    top: 70%;
```

**Comment by composerrequirer** [comment]
Ignore this last pull request, I didn't see the message.

**Comment by davidtaing** [comment]
Up to you how you want to approach it. You can run a git revert or create a new PR. Whichever is easiest for you would be fine.

Regarding the app breaking at 280px, can you please create a GitHub issue? We'll have to standardise all of our processes, so you might want to copy the structure from one of my issues.

**Comment by davidtaing** [comment]
And can you please comment on the original issue so that I can assign you to it?

https://github.com/codesydney/migram-frontend/issues/59

**Comment by composerrequirer** [comment]
I just need to comment on the issue, right?

**Review by composerrequirer — COMMENTED** [review]
padding:0px moved up, default header. fixes 60

**Comment by davidtaing** [comment]
This thread is for your pull request. Can you please click on this -> #59. And comment there? Just say that you would like to work on the issue or something. It doesn't really matter what you type.

**Comment by davidtaing** [comment]
All done, congratulations on your first PR!

**Comment by composerrequirer** [comment]
Ok, I'll try to open an issue on the breaking. Thanks

**Pull request merged**
