### PR TITLE
responsivity fix mobile s

### LINKED ISSUE #61: Bug: Homepage breaks on size 324px
It's caused by the font size of "Illawarra Multicultural Services" title.

### PR DESCRIPTION
**Pull request by composerrequirer**
Responsivity fixes #61

### CODE REVIEW

**Review by davidtaing — COMMENTED** [review]
Can you please delete the changes to the Header.tsx Component?

We won't support resolutions below 320px. Most of the entry level phones here in Australia have 480px widths.

Also with the changes to the heading on the BodyStyles.tsx component. Can you please explain how you came up with the numbers for the max-widths?

Edit: Forgot to mention that you forgot a curly bracket for the .homeTitle CSS class.

**Review by composerrequirer — COMMENTED** [review]
I removed the media query and just left the font size adjustment.

**Comment by composerrequirer** [comment]
Do you think it looks good?

**Comment by davidtaing** [comment]
What are your thoughts on doing this instead?

```css 
.homeTitle {
    @media (max-width: 900px) {
      font-size: 36px;
    }
  }

  .subTitle {
    @media (max-width: 900px) {
      font-size: 20px;
    }
  }
```

**Comment by composerrequirer** [comment]
I tested and it works fine, can you make this change or do you want me to make it?

**Comment by composerrequirer** [comment]
Just to make things clear, I meant that the changes you suggested are working fine.

**Comment by davidtaing** [comment]
Can you please do it? I'll accept the submission afterwards.

I'll go to sleep soon, so I'll have to sort it out tomorrow.

**Review by composerrequirer — COMMENTED** [review]
Changes made.

**Comment by composerrequirer** [comment]
If everything is right with this last commit, I'd like to close this issue. Is it ok if I close it?

**Comment by composerrequirer** [comment]
I think my last commit was outdated because it says my fork is some commits behind. Is it going to cause any problems?

**Comment by davidtaing** [comment]
It should be fine to merge. I'll handle any merge conflicts.

**Comment by davidtaing** [comment]
Closing this one as we are looking into redo-ing the landing page.

**Pull request closed without merging**
