### PR TITLE
fix: Hamburger Menu Signup Button Click Not Working

### LINKED ISSUE #48: Bug: Sign Up Button Cannot Be Clicked on Homepage on Viewports < 820px Width
# Description

On viewports, less than 820 px in width, the "Sign Up" button cannot be clicked on the Homepage. The IMS Banner appears to be sitting on top of most of the button. Note: Clicking at the very top of the button still works, but clicking on the lower half doesn't.

**Severity: Minor**

## Expected Behavior

- When the button is clicked, the app should navigate to the sign up page.

## Actual Behavior

- The button is unresponsive to clicks and nothing happens.

## Screenshots

j2UoU7ye27

## To Reproduce

1. Navigate to the homepage.
2. Open your browser's DevTools.
3. Click on the "Toggle Device Toolbar" in Chrome or the "Responsive Design Mode" in Firefox.
4. Select a viewport less than 820 pixels wide.
5. Try to click on the button (in the lower half is preferred).

### PR DESCRIPTION
**Pull request by MReyna12**
Fixes #48 

The original margin-top was not enough to allow for users to interact with the sign-up button, so I increased the margin-top to push the `<div>` containing the IMG text + gray square down a bit more.

Screenshot below to show cursor hover now working as intended:

ims-button
.

### CODE REVIEW

**Comment by davidtaing** [comment]
Hi @MReyna12,
It look's like the logo and containing div is still clipping the sign up button. Can you think of another way to approach this bug?

image

The BodyStyles component is currently used as our Global CSS component, so I'd prefer not to adjust the margin. This change would affect all of the other pages as well.

**Comment by davidtaing** [comment]
Hint: The Logo is sitting at the top of the button.

**Comment by MReyna12** [comment]
> Hint: The Logo is sitting on top of the button.

Understood on not wanting to adjust the margin on the global CSS component. An alternative would be to add z-index to the `<ul>` that contains the two buttons. This would allow the dropdown to cover the logo and give the user the ability to click the sign-up button. However, it would cover a portion of the IMS logo.

**Comment by davidtaing** [comment]
Good stuff! Changing the z-index was what I had in mind and good job at recognizing that a portion of the IMS logo will be covered.

I think we can go ahead with a change to the z-index and revisit adding a top margin at a later date.

**Comment by davidtaing** [comment]
Sorry, I forgot to mention that I'm okay with the menu covering a portion of the logo.

We might look into making the menu cover the whole viewport and we might not need to add any additional margin.

**Comment by MReyna12** [comment]
Understood! I'll add the z-index to the HeaderStyles.

**Review by davidtaing — CHANGES_REQUESTED** [review]
Can you please revert the first commit that adds the margin? I believe the command is something like `git revert f54b95f5`.

And can you please change the z-index to 100? We want to have a good buffer here incase someone else wants to use z-indexes for their components. You can't go wrong with 100.

**Pull request closed without merging**
